---
name: Build Test

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-test:
    name: Build test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install npm packages
        run: npm ci
        shell: bash

      - name: Build test
        run: npm run build
